package com.sso.service.dao;


import com.sun.tools.javac.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.projectshop.pojo.MoviceContentExample;
import org.projectshop.pojo.MoviceContent;
import org.springframework.stereotype.Component;

@Mapper
@Component
public interface MoviceContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movice_content
     *
     * @mbggenerated
     */
    int countByExample(MoviceContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movice_content
     *
     * @mbggenerated
     */
    int deleteByExample(MoviceContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movice_content
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movice_content
     *
     * @mbggenerated
     */
    int insert(MoviceContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movice_content
     *
     * @mbggenerated
     */
    int insertSelective(MoviceContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movice_content
     *
     * @mbggenerated
     */
    List<MoviceContent> selectByExample(MoviceContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movice_content
     *
     * @mbggenerated
     */
    MoviceContent selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movice_content
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MoviceContent record, @Param("example") MoviceContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movice_content
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MoviceContent record, @Param("example") MoviceContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movice_content
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MoviceContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movice_content
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MoviceContent record);
}