package com.sso.service.dao;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.projectshop.pojo.MoviceRoleExample;
import org.projectshop.pojo.MoviceRole;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component
public interface MoviceRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movice_role
     *
     * @mbggenerated
     */
    int countByExample(MoviceRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movice_role
     *
     * @mbggenerated
     */
    int deleteByExample(MoviceRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movice_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movice_role
     *
     * @mbggenerated
     */
    int insert(MoviceRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movice_role
     *
     * @mbggenerated
     */
    int insertSelective(MoviceRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movice_role
     *
     * @mbggenerated
     */
    List<MoviceRole> selectByExample(MoviceRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movice_role
     *
     * @mbggenerated
     */
    MoviceRole selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movice_role
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MoviceRole record, @Param("example") MoviceRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movice_role
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MoviceRole record, @Param("example") MoviceRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movice_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MoviceRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movice_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MoviceRole record);
}