package com.sso.service.dao;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.projectshop.pojo.MoviceExample;
import org.projectshop.pojo.Movice;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component
public interface MoviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movice
     *
     * @mbggenerated
     */
    int countByExample(MoviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movice
     *
     * @mbggenerated
     */
    int deleteByExample(MoviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movice
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movice
     *
     * @mbggenerated
     */
    int insert(Movice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movice
     *
     * @mbggenerated
     */
    int insertSelective(Movice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movice
     *
     * @mbggenerated
     */
    List<Movice> selectByExample(MoviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movice
     *
     * @mbggenerated
     */
    Movice selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movice
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Movice record, @Param("example") MoviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movice
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Movice record, @Param("example") MoviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movice
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Movice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movice
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Movice record);
}